// Code generated by MockGen. DO NOT EDIT.
// Source: dynamodb.go
//
// Generated by this command:
//
//	mockgen -source=dynamodb.go -destination=dynamodb_mock.go -package=client -write_package_comment=false
//

package client

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIDynamoDB is a mock of IDynamoDB interface.
type MockIDynamoDB struct {
	ctrl     *gomock.Controller
	recorder *MockIDynamoDBMockRecorder
	isgomock struct{}
}

// MockIDynamoDBMockRecorder is the mock recorder for MockIDynamoDB.
type MockIDynamoDBMockRecorder struct {
	mock *MockIDynamoDB
}

// NewMockIDynamoDB creates a new mock instance.
func NewMockIDynamoDB(ctrl *gomock.Controller) *MockIDynamoDB {
	mock := &MockIDynamoDB{ctrl: ctrl}
	mock.recorder = &MockIDynamoDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDynamoDB) EXPECT() *MockIDynamoDBMockRecorder {
	return m.recorder
}

// CheckTableDeletionProtection mocks base method.
func (m *MockIDynamoDB) CheckTableDeletionProtection(ctx context.Context, tableName *string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTableDeletionProtection", ctx, tableName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTableDeletionProtection indicates an expected call of CheckTableDeletionProtection.
func (mr *MockIDynamoDBMockRecorder) CheckTableDeletionProtection(ctx, tableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTableDeletionProtection", reflect.TypeOf((*MockIDynamoDB)(nil).CheckTableDeletionProtection), ctx, tableName)
}

// DisableTableDeletionProtection mocks base method.
func (m *MockIDynamoDB) DisableTableDeletionProtection(ctx context.Context, tableName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableTableDeletionProtection", ctx, tableName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableTableDeletionProtection indicates an expected call of DisableTableDeletionProtection.
func (mr *MockIDynamoDBMockRecorder) DisableTableDeletionProtection(ctx, tableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableTableDeletionProtection", reflect.TypeOf((*MockIDynamoDB)(nil).DisableTableDeletionProtection), ctx, tableName)
}

// CheckTableExists mocks base method.
func (m *MockIDynamoDB) CheckTableExists(ctx context.Context, tableName *string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTableExists", ctx, tableName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTableExists indicates an expected call of CheckTableExists.
func (mr *MockIDynamoDBMockRecorder) CheckTableExists(ctx, tableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTableExists", reflect.TypeOf((*MockIDynamoDB)(nil).CheckTableExists), ctx, tableName)
}

// DeleteTable mocks base method.
func (m *MockIDynamoDB) DeleteTable(ctx context.Context, tableName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTable", ctx, tableName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTable indicates an expected call of DeleteTable.
func (mr *MockIDynamoDBMockRecorder) DeleteTable(ctx, tableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTable", reflect.TypeOf((*MockIDynamoDB)(nil).DeleteTable), ctx, tableName)
}
